spring:
  datasource:
    url:
      jdbc:postgresql://localhost:5432/pizzeria
    username: postgres
    password: Martin2020@
  jpa:
    hibernate:
      ddl-auto: update
      dialect:
        org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.non-contextual-creation: true
      properties:
        hibernate:
    show_sql: true
